config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-processing:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-processing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-scarlet-zebu.sh
        container: qc.acc_scaly-tangerine-lemming
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-processing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-maroon-bird.sh
        container: qc.doc_cheeky-periwinkle-camel
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-olivine-seahorse.sh
        container: qc.doc_dorky-chocolate-zorse
      github.com/WORSICA/eosc-worsica-processing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-lilac-skunk.sh
        container: qc.doc_woozy-chartreuse-hare
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-processing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chocolate-nightingale.sh
        container: qc.lic_bumpy-persimmon-spaniel
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-processing cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-grey-dachshund.sh
        container: qc.met_crabby-fuchsia-chin
      github.com/WORSICA/eosc-worsica-processing validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-corn-wasp.sh
        container: qc.met_shabby-aquamarine-skunk
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-processing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-lilac-blue.sh
        container: qc.sec_wheezy-cardinal-lizard
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-processing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cardinal-bear.sh
        container: qc.sty_cranky-goldenrod-birman
      github.com/WORSICA/eosc-worsica-processing jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-black-gecko.sh
        container: qc.sty_bluesy-scarlet-heron
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-processing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-salmon-caiman.sh
        container: qc.ver_leaky-cerulean-dragon
timeout: 1800
