config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-processing:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-processing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-puce-manatee.sh
        container: qc.acc_woolly-saffron-dachsbracke
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-processing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lilac-chameleon.sh
        container: qc.doc_shaky-champagne-loon
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-rose-indri.sh
        container: qc.doc_fuzzy-chartreuse-quoll
      github.com/WORSICA/eosc-worsica-processing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amaranth-whippet.sh
        container: qc.doc_crabby-gold-cichlid
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-processing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-brown-duck.sh
        container: qc.lic_trippy-cornflower-birman
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-processing cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-orchid-impala.sh
        container: qc.met_stuffy-yellow-dugong
      github.com/WORSICA/eosc-worsica-processing validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cinnamon-russel.sh
        container: qc.met_smelly-denim-jaguar
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-processing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-brass-panda.sh
        container: qc.sec_silly-orange-lynx
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-processing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-khaki-wallaby.sh
        container: qc.sty_bluesy-thistle-cat
      github.com/WORSICA/eosc-worsica-processing jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-white-coral.sh
        container: qc.sty_pretty-cinnamon-snail
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-processing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-charcoal-corgi.sh
        container: qc.ver_nippy-cerise-fly
timeout: 1800
