config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-processing:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-processing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-auburn-numbat.sh
        container: qc.acc_ugly-lime-gecko
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-processing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-violet-wolf.sh
        container: qc.doc_snoopy-brass-cat
      github.com/WORSICA/eosc-worsica-processing git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sapphire-bombay.sh
        container: qc.doc_pokey-cinnamon-bird
      github.com/WORSICA/eosc-worsica-processing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-bistre-ragdoll.sh
        container: qc.doc_ready-periwinkle-cow
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-processing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-vermilion-earwig.sh
        container: qc.lic_pasty-wisteria-centipede
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-processing cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-azure-buzzard.sh
        container: qc.met_flaky-teal-affenpinscher
      github.com/WORSICA/eosc-worsica-processing validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-teal-dunker.sh
        container: qc.met_craggy-seashell-quetzal
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-processing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lime-macaw.sh
        container: qc.sec_squeaky-bronze-havanese
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-processing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-russet-malamute.sh
        container: qc.sty_flabby-crimson-dollar
      github.com/WORSICA/eosc-worsica-processing jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-tomato-cattle.sh
        container: qc.sty_sleazy-teal-cat
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-processing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-seashell-mouse.sh
        container: qc.ver_woolly-sepia-dachsbracke
timeout: 1800
